# SEGMENTATION
distance_threshold: 30 # 3 * safety_distance

base_size: [10, 20]
safety_margin: 5

# PATH PLANNING
# safety_distcance: round_up(base_size[0]/2 + safety_margin)
min_rectangle_size: 1600 # 4 * (2*safety_distance)**2
min_corridor_width: 20 # 2*safety_distance
min_corridor_height: 20 # 2*safety_distance
max_rectangle_to_line_width: 55 # 5.5 * safety_distance
max_rectangle_to_line_height: 55 # 5.5 * safety_distance