# request

---
# response
string next_floor
uint8 floor_marker_id
uint8 call_button_marker_id
geometry_msgs/Pose waiting_start
geometry_msgs/Pose waiting_goal
geometry_msgs/Point panel_start
geometry_msgs/Point panel_goal