# request

---
# response
string next_floor
uint8 marker_id
string direction
float64 orientation_angle
geometry_msgs/Point call_button
geometry_msgs/Point selection_panel
geometry_msgs/Pose next_floor_start